KNN
francescoopiccoli/MLBio_project pull request #2
Opened 2023-03-17 20:05 UTC by WortelSoep

Implements KNN model for 1bp insertions

2023-03-19 11:14 UTC, francescoopiccoli requested changes

2023-03-19 11:14 UTC, francescoopiccoli commented on Knn_helper.py
> +  # rate_stats = rate_stats[rate_stats['Entropy'] > 0.01]
```
# Check better the output of this merge operation
  all_rate_stats = pd.merge(all_rate_stats, knn_features, left_on='exp', right_on='exp', how='left')

  print(all_rate_stats)  
```

2023-03-19 11:14 UTC, francescoopiccoli commented on Knn_helper.py
> +def train_knn(knn_features, data_nm):
```suggestion
def train_knn(knn_features, count_and_deletion_df):
```

2023-03-19 11:14 UTC, francescoopiccoli commented on Knn_helper.py
> +def calc_statistics_1bp(df, exp, alldf_dict):
I would delete all the commented parts for now, I think we need this only once the knn is trained
```suggestion
def calc_statistics_1bp(df, exp, alldf_dict):
  pass
```

2023-03-19 11:14 UTC, francescoopiccoli commented on Knn_helper.py
> +    print(ent.shape, fivebases.shape, del_scores.shape)
```suggestion
    total_del_phis = np.array(rate_stats['total_del_phi']).reshape(len(rate_stats['total_del_phi']), 1)
    precision_scores_dl = np.array(rate_stats['precision_score_dl']).reshape(len(rate_stats['precision_score_dl']), 1)
    print(total_del_phis.shape, fivebases.shape, precision_scores_dl.shape)
```

2023-03-19 11:14 UTC, francescoopiccoli commented on Knn_helper.py
> +  # alldf_dict['Ins1bp/Del Ratio'].append(ins_count / (del_count + ins_count))
If I understood correctly we need these lines, we'll use them as the y/label/target of the knn:
```
# Line 965 and 966 of the supplementary material.
  ins_criteria = (df['Type'] == 'INSERTION') # & (dcount_and_deletion_dff['Length'] == 1)
  ins_count = sum(df[ins_criteria]['countEvents'])

  del_criteria = (df['Type'] == 'DELETION')
  del_count = sum(df[del_criteria]['countEvents'])
  # Not sure why of these lines
  #if del_count == 0:
    #return
  alldf_dict['Ins1bp/Del Ratio'].append(ins_count / (del_count + ins_count))
```
The rest of the commented lines can be deleted I think.

2023-03-19 11:14 UTC, francescoopiccoli commented on Knn_helper.py
> +  cutsite = (int) (len(exp) / 2)
I think we need to cut at position 17, and the take the fivebase  the element at that position, and as three base the element at position 18. 
We need to take into account the thing at the beginning of the sequence: 0_0_0_0..

2023-03-19 11:14 UTC, francescoopiccoli commented on Knn_helper.py
> +  insertion_data = data_nm[data_nm['Type'] == 'INSERTION'].reset_index()
I dont understand why we keep into account only the insertions.
Shouldn't we compute the statistics for both deletions and insertions?

2023-03-19 11:14 UTC, francescoopiccoli commented on Knn_helper.py
> +    X = np.concatenate(( gtag, ent, del_scores), axis = 1)
Why is this here twice

2023-03-19 11:14 UTC, francescoopiccoli commented on Knn_helper.py
> +  all_bp_stats = pd.DataFrame()
Not sure if we will need two of these, what's the difference, cant we put all data in one?

2023-03-20 10:42 UTC, WortelSoep commented on Knn_helper.py
> +    X = np.concatenate(( gtag, ent, del_scores), axis = 1)
I took this code from the authors as is, it appears to be a mistake indeed

2023-03-20 10:43 UTC, WortelSoep commented on Knn_helper.py
> +  # alldf_dict['Ins1bp/Del Ratio'].append(ins_count / (del_count + ins_count))
I agree, I'll have to compare to the authors code one more time but this seems to make sense :)

2023-03-20 10:44 UTC, WortelSoep commented on Knn_helper.py
> +  all_bp_stats = pd.DataFrame()
I think the bp stats are different in that they are only calculated for the insertions, but not entirely sure

2023-03-20 10:45 UTC, WortelSoep commented on Knn_helper.py
> +  insertion_data = data_nm[data_nm['Type'] == 'INSERTION'].reset_index()
Yes this was my mistake, I think the bp method should use only insertions. For the other method both shoudl be included

2023-03-20 10:48 UTC, WortelSoep commented on Knn_helper.py
> +  # rate_stats = rate_stats[rate_stats['Entropy'] > 0.01]
The authors do this differently but I guess merging it like this should also be fine?

  if del_count == 0:
    return

This might matter but not entirely sure

2023-03-20 15:22 UTC, merged